name: "🐞 bug"
description: "버그 이슈 추가"
body:
  - type: textarea
    attributes:
      label: 📄 버그 설명
      description: 버그에 대한 설명을 작성해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: ⚙ 해결방안
      description: 해결 방법에 대해 작성해 주세요.
      placeholder: 결정된게 없어도 됩니다.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.
